### ISSUE TITLE
Input and Map

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#2]
## Value Preposition

**As a User**  
**I need** to know the route between two locations
**to be able to** see the distance between locations

## Description
 
![Bildschirmfoto 2021-11-28 um 18 51 19](https://user-images.githubusercontent.com/91472321/143780426-9a85c787-c6a8-40ae-9888-81135d7e518c.png)

## Acceptance Criteria
- [x] Input fields must not be empty, if so, show a warning
- [x] #18
- [x] Button leads to Map-page if all inputs are valid
- [x] Map-page has a Back Button that leads to Input-page
- [x] if coming back to input page by back button, the input fleids shoud be empty
- [x] Map-page shows both locations with incon, the directions as line

## Tasks

- [x] create form component
- [x] create Map component 
- [x] create component for back button
