### ISSUE TITLE
Style

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#20]
## Value Preposition

**As a User**
**I need** to navigate throu the app in a easy and fun way
**to be able to** keep the app using the app

## Description ( text, scribbles, images, designs)
![Scribble V 02](https://user-images.githubusercontent.com/91472321/144830772-54dc6f00-c94b-480c-b04a-0449e9251b8d.png)

## Acceptance Criteria
- [x] Make a design that clear and easy to use
- [x] decide for a good color scheme

## Tasks
- [x] decide for a layout
- [x] decide for color theme
