### ISSUE TITLE
List Locations

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#3]
## Value Preposition

**As a User**
**I need** to find the locations and middle point as text
**to be able to** overwiew all informations very quick.

## Description
![Bildschirmfoto 2021-11-22 um 11 27 44](https://user-images.githubusercontent.com/91472321/142845321-03f6564c-37f0-4c1b-b710-adbb51fd1022.png)

Under Locations, the inputs from Input-page are listed. 
Under Places the calculated middle is listed 

## Acceptance Criteria
- [x] by ckick at all List -items lead back to Map-page with directions
- [x] Map button leading back to Map-page
- [x] Locations lists the inputs
- [x] Places lists the calculated middle as adess or coordination data. 

## Tasks
- [x] create List component that lists location and places
- [x] create Map button to lead back to Map-page as form of the back button component
- [x] create List button in Map-page to lead to List-page form of the back button component
