### ISSUE TITLE
View Places Details on Map

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#39]
## Value Preposition

**As a User**
**I need**te view some Details about Places 
**to be able to** decide for e.g. a restaurant or a hotel

## Description 

![Bildschirmfoto 2021-12-10 um 15 38 36](https://user-images.githubusercontent.com/91472321/145591176-68722fa3-fbd5-4caf-8520-1123011b0fb7.png)

## Acceptance Criteria
- [x] when clicked or tabed on one place, open a popup
- [x] show some information e.g. Name and Price

## Tasks

- [x] use teh Mapbox Popup
- [x] use information from fouresquare Api
