### ISSUE TITLE
Navigation

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#4]
## Value Preposition

**As a User**
**I need**to navigate 
**to be able to** be able to jump between three main pages

## Description 
![Bildschirmfoto 2021-11-20 um 12 15 24](https://user-images.githubusercontent.com/91472321/142724309-fece6a0d-93d1-43a0-af05-9a2b23f70752.png)

## Acceptance Criteria
- [ ] Navigation shows in every page
- [ ] actual page is shown in navigation list as different color or style
- [ ] by clicking on Map-icon the Map-page is shown
- [ ] if no new input was submitted, Map shows with last valid locations
- [ ] by clicking List-Icon, List-page will show with last valid input
- [ ] by clicking input(NEW)-incon (former back button), input page is shown with empty form

## Tasks

- [ ] create Navigation component
- [ ] get current page and highligt it in navigation
- [ ] create Links beween pages
- [ ] integrate Navigation-component on all existing pages

**Comment by julialoeschel** [comment]
the desing dont need a nav bar anymore - issue will be closed.
