### ISSUE TITLE
Place Options-component

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#5]
## Value Preposition

**As a User**
**I need** to specify what im looking for in the calculated middle place
**to be able to** to decide about a meeting place 

## Description 

![Bildschirmfoto 2021-11-22 um 11 36 25](https://user-images.githubusercontent.com/91472321/142846672-5d0308b9-e8d9-4df7-b8c8-98584fc81787.png)

## Acceptance Criteria
- [x] combine Inplace and InDistance
- [ ] #40
- [x] if only tags are activ, show default map on map page
- [x] if place and Distance are set, show all active places within the distance on the map
- [x] no submit button, just tab the map button after finish settings

## Tasks
(for developers)
- [x] create component "InMiddle"
- [x] combine InDistance and InPlace and InDistance
- [ ] ...
