### ISSUE TITLE
InDistance - component

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#6]
## Value Preposition

**As a User**
**I need** to specify the search area
**to be able to** find a suitable place to meet

## Description 
![Bildschirmfoto 2021-11-20 um 12 38 28](https://user-images.githubusercontent.com/91472321/142724948-e3ec2516-19fd-41d9-b085-a8780627b8fb.png)

## Acceptance Criteria
- [x] input scale that shows km
- [x] beween 0 and 50km
- [x] Naming shall state "Radius" and "km"

## Tasks

- [x] create component for inRadius
- [x] input field for numbers with onChange
- [x] input values shall be send to "placeOption" component
