### ISSUE TITLE
InPlace - component

### ISSUE THREAD

**Issue by julialoeschel** [julialoeschel/capstone-project#7]
## Value Preposition

**As a User**
**I need** to choose a map tag
**to be able to** view my possiblities on the map

## Description 

![Bildschirmfoto 2021-11-20 um 12 45 50](https://user-images.githubusercontent.com/91472321/142725179-651f6f38-2a59-49f3-8d19-3065070d2fbb.png)

## Acceptance Criteria
- [x] Show three Tags for places to choose from
- [x] toggle style when active
- [x] Text shall state "What are you looking for?" or similar

## Tasks

- [x] create Tag component
- [x] make Tag toggle and save state
- [x] create Taglist
- [x] move state to taglist
